### ISSUE TITLE
original link of GCC RLE

### ISSUE THREAD

**Issue by wxie2017** [narukeu/GCC_RLE_3.1_ZH_CN#1]
Thanks for the contribution.
Could you please put the original link of GCC RLE in the README.md?

It would be better that you also add the original link in your translation:
只有 GCC RLE 的[原始英文版](url)才有法律意义

wxie

**Comment by narukeu** [comment]
Thank you for your suggestion. I have added a link to the original text.

**Comment by wxie2017** [comment]
Thank you. This is good. I will close it.
