### ISSUE TITLE
review-1: 本例外条款的目的是允许编译非 GPL（包括专有）程序，以此方式使用本例外所涵盖的头文件和运行时库。

### ISSUE THREAD

**Issue by wxie2017** [narukeu/GCC_RLE_3.1_ZH_CN#2]
本例外条款的目的是允许编译非 GPL（包括专有）程序，以此方式使用本例外所涵盖的头文件和运行时库。
I suggest add a "时", like
本例外条款的目的是允许编译非 GPL（包括专有）程序时，以此方式使用本例外所涵盖的头文件和运行时库。

**Comment by narukeu** [comment]
All Fixed,Thank you!
